# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eadcb7117dd567f8f23250c5b83932c13f5505e2f3a3312e4aecad062aa9527c1350969012a294c5f54cd1aa1bc79107be830fc51730a4c4fe68f290c69f7b4b

test:
  secret_key_base: 7e8f35cfc80c6840ad4b8013d6b0e383115eae1459ab24cbef36137c8a00812bd05c54ca49326d001d244aa8ba8cd5bde43843cf5518da6e7b12a45525a079c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
